### PR TITLE
Added link to fb-flo-plugin -- finally!

### PR DESCRIPTION
**Pull request by tdd**
Hey guys,

Guess what? `fb-flo-brunch` is finally here, and it's awesome! Figured I'd add it to the list, next to its "colleagues".

### CODE REVIEW

**Comment by paulmillr** [comment]
interesting

**Comment by tdd** [comment]
Hey Paul! Thanks. Just wrapped it up, 'been wanting it for a while, finally got around to implementing it. The full test suite is in, too. I love the super-fast feedback loop this gives me, including JS, if only in Chrome for now…

If you feel like it, wouldn't say no to a tweet or two on the Brunch account, ideally at good US times :wink:

**Comment by tdd** [comment]
BTW do we need to do anything special to publish this now?

**Comment by paulmillr** [comment]
no, nothing special

**Comment by tdd** [comment]
Ah, I must have missed something then. Didn't `brunch build` or `grunt publish`,thought you would. So the GitHub pages are not up-to-date with the Jade template, and I don't see this online.

**Comment by es128** [comment]
Yeah there's a build step. I'll take care of it today.

**Comment by es128** [comment]
done

**Comment by tdd** [comment]
Thanks! :-)

-- 
Christophe Porteneuve
tdd@tddsworld.com

**Pull request merged**
