### PR TITLE
Move site build into source branch

### PR DESCRIPTION
**Pull request by denar90**
@paulmillr @shvaikalesh @denysdovhan I created new PR for merging stuff into `source` branch. 

I just have one concern. What about `README.md`? Do we have to put it into `app\assets\README.md` so it will be shown for everyone in master branch (because it will be moved into root level after build/deploy)?

And also I'm waiting for secure key.

### CODE REVIEW

**Comment by paulmillr** [comment]
Let's put the readme there, yes.

**Comment by paulmillr** [comment]
Thank you!

Let's put the readme there, yes. I'll try to add the travis today.

**Comment by denar90** [comment]
Nice 💃  ✈️

**Comment by denysdovhan** [comment]
Thanks for contributing @denar90!

**Comment by paulmillr** [comment]
@denar90 what did you mean by github access token? Would it allow third-parties to access my private repositories?

**Comment by denar90** [comment]
@paulmillr as I understand, regarding to docs, it's absolutely secure - https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml

**Comment by denar90** [comment]
@paulmillr other then that you can use another way.
Easy generate `gh-token` like this 
image

and add it to Travis
image

It will be totally secure and nobody either will see or will get access to your other repos.

**Pull request merged**
