### PR TITLE
Move search CTA from top of page to bottom

### PR DESCRIPTION
**Pull request by jhabdas**
Users may not notice the search link at the top of the page and hit a dead-end when they get to the bottom. Moving the NPM search link to the bottom will give them a good place to continue exploring for plug-ins.

### CODE REVIEW

**Comment by es128** [comment]
how about leaving it in both places?

**Comment by jhabdas** [comment]
Done. Also do you know if these templates are fitted with a markdown parser that supports GitHub flavored markdown like RedCarpet?

**Comment by es128** [comment]
idk perhaps you will find answers in https://github.com/jadejs/jade/issues/363

**Comment by jhabdas** [comment]
Nice find. I'll see what I can get away with on my next pull with the current version.

**Pull request merged**
