### PR TITLE
Get rid of grunt

### PR DESCRIPTION
**Pull request by goshakkk**
https://github.com/brunch/brunch/issues/1164

* replaces the `grunticon` task with a direct invocation of its underlying lib for svg processing
* replaces the `gh-pages` task with a `git subtree push` (that requires the `public/` be stored in source control)

re what @paulmillr was asking me about, It doesn't look like it's possible to have everything in master — because the root of master is the root of the website (and ours is in public...)

### CODE REVIEW

**Comment by paulmillr** [comment]
> and ours is in public

`config.paths.public = '.'`

**Comment by paulmillr** [comment]
We can also make a separate directory for the whole brunch app and then set the public path to `..`.

**Comment by goshakkk** [comment]
but isn't that going to be, like, really, really messy? another solution could be to have the sources inside the `source` folder, and output public to the root (aka `..` from `source)

**Comment by goshakkk** [comment]
Yup, ok

**Comment by goshakkk** [comment]
Done!

**Pull request merged**
