### PR TITLE
Fix link to notifications section in menu

### PR DESCRIPTION
**Pull request by Arcesilas**

### CODE REVIEW

**Comment by Arcesilas** [comment]
Sorry, I forgot to change this in the previous PR.

**Comment by paulmillr** [comment]
Conflicting files
app/assets/_docs/config.md
Squash and merge

**Comment by Arcesilas** [comment]
Is that because there are 2 commits? It's supposed to be only one... I'll take a look.

**Comment by Arcesilas** [comment]
I've solved the conflict, but maybe you prefer a PR with one single clean commit?

**Pull request merged**
